## 数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/flow-demo?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: GTMCmail8800
  # spring.datasource.druid.driver-class-name=com.mysql.jdbc.Driver
  # 连接池配置(通常来说，只需要修改initialSize、minIdle、maxActive
  # 如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。removeabandoned不建议在生产环境中打开如果用SQL Server，建议追加配置)
      initial-size: 10
      max-active: 40
      min-idle: 5
  # 配置获取连接等待超时的时间
      max-wait: 60000
  # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  # spring.datasource.druid.max-open-prepared-statements=和上面的等价
      validation-query: SELECT 'x'
  # spring.datasource.druid.validation-query-timeout=
      test-on-borrow: false
      test-on-return: false
      est-while-idle: true
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  #spring.datasource.druid.max-evictable-idle-time-millis=

  #log path config
log:
  path: d:\\data\\applogs\\flow
  level: INFO

  # base path
bath:
  path: http://localhost:8989